---
title: "About Class"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
```

**Instructors**:  
Rachel Schwartz  
CBLS 377  
4-5404  
rsschwartz@uri.edu 

Please note that the instructor will do her best to respond promptly between 9-5 on weekdays.

**Office Hours**: TBD   
Please feel free to come by without an appointment during this time. To talk with me during other times please set up a meeting by email.

**Class Days / Time**: W 2-3pm CBLS 435

**Prerequisites**: Enrolled in a BES graduate program

**Texts**:   

Data Viz:  
* [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/index.html)  
* [How to pick your visualization / chart](https://www.data-to-viz.com/)  
* [More references](https://datavizf18.classes.andrewheiss.com/reference/)


**Other equipment / material requirements**:

**Assignments**:  
Present your research

**Grades**:

S/U

**Special notes**:
If you, or anyone you know, is at risk of going hungry please visit the Rhody Outpost, a food pantry operated by URI. Rhody Outpost is open twice per month at St. Augustine Church at 15 Lower College Rd. For open hours see https://web.uri.edu/deanofstudents/rhody-outpost/ . Rhody Outpost protects the privacy of all visitors. Students may also visit the Jonnycake Center in Peace Dale.

Counseling and Psychological Services: 
Graduate school can be complicated and challenging. You might feel overwhelmed, experience anxiety or depression, or struggle with relationships or family responsibilities. The [URI Counseling Center](https://web.uri.edu/counseling/) provides confidential support for the personal, emotional, and academic well-being of our students. These services include individual counseling, group counseling, and referrals.