---
title: "BIO 263 URI Fall 2018"
subtitle: "Ecological Data Analysis"
author: "Instructor: Rachel Schwartz"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: cosmo
---
## Overview

This course is intended to help you learn how to analyze ecological data. In the process you will gain general quantitative skills, reinforce the concepts your are learning / have learned in BIO 262 (Ecology), and learn how to integrate concepts to answer biological questions. These skills are broadly applicable to various careers requiring critical thinking, and are directly applicable to pursuing a career in research or applied ecology. This course will consist of limited lecture time and extensive hands-on time. It is expected that prior to this course you have taken BIO 104 with labs using R for data analysis. Alternatively, discuss substitute prerequisites with the instructor.

## Course Goals:
At the end of this course students enrolled in BIO263X should... 
* be familiar with ecological data at di erent scales.
* understand basic methods to analyze ecological datasets.

## Student Learning Outcomes:
At the end of this course students enrolled in BIO263X should be able to...
* plot relationships among variables in a dataset using R.
* select appropriate statistical tests to compare groups of data and understand trends. 
* run basic statistical tests using R.