---
title: "Class Materials"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Day 1   
[Planned activities and schedule](https://docs.google.com/document/d/1ejvs0rUF-ixUqaQmoCR4T3JgGvwPypIMFJdAJmPrIZ4/edit?usp=sharing)

## Day 2: Data Viz and figures
* [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/index.html)  
* [How to pick your visualization / chart](https://www.data-to-viz.com/)  
* [More references](https://datavizf18.classes.andrewheiss.com/reference/)

## Day 3: Slide / poster design
* [The art of slide design](https://missgeeky.com/2017/08/04/the-art-of-slide-design/)  
* [How to design a poster](https://www.animateyour.science/single-post/How-to-design-an-award-winning-conference-poster)  
* [Class slides](howtomakeaposter.pdf)  
* [Gig posters for scientists](https://www.flickr.com/photos/biologyposters/)
* [Alternative poster design](https://www.youtube.com/watch?v=1RwJbhkCA58&feature=youtu.be)
*[Poster as a prop](https://medium.com/@jjmerelo/make-your-poster-presentation-awesome-97d021258d78)
* [Infographic examples](https://www.animateyour.science/gallery)

## Day 4: Giving good talks
* [How to structure a talk](http://rajlaboratory.blogspot.com/2016/09/some-thoughts-on-how-to-structure-talk.html)  
* [Class slides](howtomakeapresentation.pdf)  
* [Tell a story](https://www.animateyour.science/single-post/Tell-Them-a-Story-How-to-Avoid-the-Standard-Boring-Presentation)  
* [Presentation dos and don'ts](https://www.animateyour.science/single-post/Conference-Presentation-Dos-and-Donts-for-Scientists)  
* [Making Powerpoint accessible](https://business.tutsplus.com/tutorials/accessible-powerpoint-presentations--cms-30018)  
* [Accessible presentations](https://www.swarthmore.edu/sites/default/files/assets/documents/academic-advising-support/Accessible%20Presentations.pdf)  
* [Ten Simple Rules for Making Good Oral Presentations](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.0030077)

## Day 5: Alexa  
* [Comment on Alexa's poster](https://docs.google.com/document/d/1wy2KmbUG2BlL4sY6NtSI_oBzavxf5mCO41f-Ca2yi58/edit?usp=sharing)  

## Day 6: Messaging
* [Message Box tool](https://www.compassscicomm.org/the-message-box-workbook)  
* [Slides](https://docs.google.com/presentation/d/17T47-He9lkwAwXW9TrXx--ZUiTYBU0iFqJI_QuU8ruY/edit?usp=sharing)  
* [Presentation response prompts](https://docs.google.com/document/d/1MVw4Hx0CAHyfmNY2IC8WEo0uHi94FUd6z2ShL_qHW_g/edit?usp=sharing)

## Day 7: Laura / Amy
* [Comment on Laura's presentation](https://docs.google.com/document/d/1NjWsWACXvojtxA6dlO4n4lZXG5nR0ao3V-2y4Xi7zIA/edit?usp=sharing)  
* [Comment on Amy's presentation](https://docs.google.com/document/d/1is9T0ebCmLdHZfrXD2oXN1QCW-g0pr2zdFpNFIq2-yk/edit?usp=sharing)

## Day 8: Aubree / Kevin
* [Aubree](https://docs.google.com/document/d/1RhsSDmUsNo8M3LtjeUzY6-askxRHZSUyvDGu0QKHtOA/edit?usp=sharing)  
* [Kevin](https://docs.google.com/document/d/1e3olQRMUFw6dY61ulSVDAjO0k1Xh1mDGts5c3XqGRKE/edit?usp=sharing)

## Day 9: Cassie / Katie  
* [Cassie](https://docs.google.com/document/d/16tpG_x0OzTCv5sRwln9Q3SnkBxQZGPvwNeZnttA7eCU/edit?usp=sharing)  
* [Katie](https://docs.google.com/document/d/1tUzacYVeFFjZDWDEeapZt7Ru26aWyGCci-P8juSkydc/edit?usp=sharing)

## Day 10: Jillian / Erin  
* [Jillian](https://docs.google.com/document/d/1-ky9CK8GAw7UbUAJLi1anDdPlq5NPBianLadtmQphF0/edit?usp=sharing)  
* [Erin](https://docs.google.com/document/d/10FpvW6uTd6vqzKwCjDC4WfI07YsTjJxwvwRtOv3BguE/edit?usp=sharing)

## Day 11: Matias / Kristina  
* [Matias](https://docs.google.com/document/d/1AWAovieRHcw1cBosPneVnNH4oC24kTZzvl32nlvxzfk/edit?usp=sharing)  
* [Kristina](https://docs.google.com/document/d/1ie-nMGnDys1s9IwsL7kncEXHMgepY3zogBoGV2mtqMo/edit?usp=sharing)

